### ISSUE TITLE
Summary of room options not (always) shown on Extras page

### ISSUE THREAD

**Issue by alexanderkoller** [alexanderkoller/ehb2#19]
For my extras at EHB 2018, the only thing I requested was a single room for the two regular nights. The order confirmation page did not show this in detail (see attached screenshot).

Instead, there should be a summary - as in earlier years - which shows all the extras items I have ordered in a table which also indicates whether I pay for each item via Paypal or settle it directly with the hotel.

![screen shot 2018-07-16 at 10 25 37](https://user-images.githubusercontent.com/8291392/42749034-9d87ec66-88e2-11e8-9074-b88a703bec52.png)

**Comment by alexanderkoller** [comment]
I just saw that the summary table is shown on the confirmation page after the Paypal payment was successfully made. This same table should also be shown before the Paypal payment.

... except that the "Your room" row now doesn't list the price for that row in the "Pay Now" column. I think this is because extra room costs are now a "pay now" item and used to be a "pay to hotel" item in the past, and it must have slipped through the cracks when the code was changed.

![screen shot 2018-07-16 at 10 28 49](https://user-images.githubusercontent.com/8291392/42749156-105a009e-88e3-11e8-879c-4a96bc0d2786.png)

**Comment by alexanderkoller** [comment]
... and same problem on the show-extras.html page, which probably uses the same table template as the extras-payment-success.html page.

**Comment by alexanderkoller** [comment]
... and the extras.html page after an extras booking was submitted and paid for.

**Comment by bumbleblue** [comment]
The table displays correctly now, but only for new entries. I'll find a way to fix the old ones as well!
[this](bfd8766bd807766a0f722ff4b28efd9e98a7a484)
